### PR TITLE
fix: change filter logic to avoid early returning

### LINKED ISSUE #1848: Not filtering by excluded handle (GHE)
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### 📝 Description

I have a handle exclusion specified in filters yet am still receiving notifications for PRs from that user.

PS thanks for Gitify, love it!

### 🪜 Steps To Reproduce

1. Using GitHub Enterprise account
2. Ensure detailed notifications is on
3. Add a handle to exclude
4. Create a PR or other notification with that user
5. Notification appears in list
### 🪵 Log Excerpts

_No response_

### Gitify Version

6.1.0

### Operating System

macOS

### GitHub Account

GitHub Enterprise Server

### 📸 Screenshots

Image

Image

Image

### PR DESCRIPTION
**Pull request by setchy**
resolves #1848

### CODE REVIEW

File: src/renderer/utils/notifications/filters/filter.ts [hunk 1]
```diff
@@ -13,33 +13,43 @@ export function filterNotifications(
...
+          settings.filterUserTypes.some((userType) =>
+            filterNotificationByUserType(notification, userType),
+          );
       }
 
       if (hasIncludeHandleFilters(settings)) {
-        return settings.filterIncludeHandles.some((handle) =>
-          filterNotificationByHandle(notification, handle),
-        );
+        passesFilters =
```
Comment (grahamj) [inline src/renderer/utils/notifications/filters/filter.ts:28]: You probably want included handles to override the user type check, eg. if you don't check User but have an included handle you'd want to pass.

so: !exclude && (type || include) && reason

Comment (setchy) [reply src/renderer/utils/notifications/filters/filter.ts:28]: Why not leave the logic as-is and treat all selected filters as an `AND` 🤔

Comment (setchy) [reply src/renderer/utils/notifications/filters/filter.ts:28]: It does mean as you pointed out (thank you for doing so), there is some interplay between `User Type` and the `Handle Filters` - but that seems OK to me.

@afonsojramos @bmulholland - interested to hear your thoughts 👂

Comment (grahamj) [reply src/renderer/utils/notifications/filters/filter.ts:28]: np, whatever you think :)

Comment (afonsojramos) [reply src/renderer/utils/notifications/filters/filter.ts:28]: I think it looks good as is. It can probably be improved with a little modularity, but it is fine as it is.

**Review by afonsojramos — APPROVED** [review]
